apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vp1gl12iq-go 
  janus-idp.io/tekton: vp1gl12iq-go
  backstage.io/kubernetes-id: vp1gl12iq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vp1gl12iq-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml