apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vp1gl12iq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vp1gl12iq-go 
  name: vp1gl12iq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vp1gl12iq-go 
